<?php

$URL = "localhost";
$USER_NAME = "root";
$PASSWORD = "root";
$DATABASE = "DeviceInformation";

$REQUEST_PORTRAIT_SCREEN_DETAILS_KEY = "portraitScreenDetails";
$REQUEST_LANDSCAPE_SCREEN_DETAILS_KEY = "landscapeScreenDetails";
$REQUEST_VERSION_CODE_NAME_KEY = "versionCodeName";
$REQUEST_VERSION_INCREMENTAL_KEY = "versionIncremental";
$REQUEST_VERSION_RELEASE_KEY = "versionRelease";
$REQUEST_VERSION_SDK_STRING_KEY = "versionSdkString";
$REQUEST_VERSION_SDK_INTEGER_KEY = "versionSdkInteger";
$REQUEST_BOARD_KEY = "board";
$REQUEST_BOOT_LOADER_KEY = "bootLoader";
$REQUEST_BRAND_KEY = "brand";
$REQUEST_CPU_ABI_KEY = "cpuAbi";
$REQUEST_CPU_ABI_2_KEY = "cpuAbi2";
$REQUEST_DEVICE_KEY = "device";
$REQUEST_DISPLAY_KEY = "display";
$REQUEST_FINGER_PRINT_KEY = "fingerPrint";
$REQUEST_HARDWARE_KEY = "hardwade";
$REQUEST_HOST_KEY = "host";
$REQUEST_DEVICE_ID_KEY = "deviceId";
$REQUEST_MANUFACTURER_KEY = "manufacturer";
$REQUEST_PRODUCT_KEY = "product";
$REQUEST_RADIO_KEY = "radio";
$REQUEST_TAGS_KEY = "tags";
$REQUEST_TIME_KEY = "time";
$REQUEST_TYPE_KEY = "type";
$REQUEST_UNKNOWN_KEY = "unkown";
$REQUEST_USER_KEY = "user";
$REQUEST_DENSITY_NAME_KEY = "densityName";
$REQUEST_SCREEN_SIZE_KEY = "screenSize";
$REQUEST_DENSITY_KEY = "density";
$REQUEST_XDPI_KEY = "xdpi";
$REQUEST_YDPI_KEY = "ydpi";
$REQUEST_COUNT_KEY = "ydpi";
$REQUEST_DEVICE_NAME_KEY = "deviceName";
$REQUEST_CANONICAL_NAME_KEY = "canonicalName";

$REQUEST_DEVICE_PIXEL_HEIGHT_KEY = "devicePixelHeight";
$REQUEST_DEVICE_PIXEL_WIDTH_KEY = "devicePixelWidth";
$REQUEST_WINDOW_PIXEL_HEIGHT_KEY = "windowPixelHeight";
$REQUEST_WINDOW_PIXEL_WIDTH_KEY = "windowPixelWidth";
$REQUEST_CONTENT_VIEW_PIXEL_HEIGHT_KEY = "contentViewPixelHeight";
$REQUEST_CONTENT_VIEW_PIXEL_WIDTH_KEY = "contentViewPixelWidth";
$REQUEST_NAV_BAR_HEIGHT_KEY = "navBarHeight";
$REQUEST_NAV_BAR_WIDTH_KEY = "navBarWidth";
$REQUEST_STATUS_BAR_HEIGHT_KEY = "statusBarHeight";
$REQUEST_TITLE_BAR_HEIGHT_KEY = "titleBarHeight";

$TABLE_NAME_DEVICE_INFORMATION = "deviceInformation";
$TABLE_NAME_FULL_DEVICE_INFORMATION = "fullDeviceInformation";
$TABLE_NAME_SCREEN_DETAILS = "screenDetails";
$TABLE_COLUMN_NAME_DEVICE_INFORMATION_ID = "deviceInformationId";
$TABLE_COLUMN_NAME_SCREEN_SIZE_ID = "screenSizeId";
$TABLE_COLUMN_NAME_IS_PORTRAIT = "isPortrait";
$TABLE_COLUMN_NAME_COUNT = "count";

$RESPONSE_SUCCESS_KEY = "success";

$TABLE_COLUMN_NAME_PORTRAIT = "portrait";
$TABLE_COLUMN_NAME_LANDSCAPE = "landscape";

$TABLE_COLUMN_PORTRAIT_DEVICE_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_DEVICE_PIXEL_HEIGHT_KEY ;
$TABLE_COLUMN_PORTRAIT_DEVICE_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_DEVICE_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_PORTRAIT_WINDOW_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_WINDOW_PIXEL_HEIGHT_KEY;
$TABLE_COLUMN_PORTRAIT_WINDOW_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_WINDOW_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_PORTRAIT_CONTENT_VIEW_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_CONTENT_VIEW_PIXEL_HEIGHT_KEY;
$TABLE_COLUMN_PORTRAIT_CONTENT_VIEW_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_CONTENT_VIEW_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_PORTRAIT_NAV_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_NAV_BAR_HEIGHT_KEY;
$TABLE_COLUMN_PORTRAIT_NAV_BAR_WIDTH_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_NAV_BAR_WIDTH_KEY;
$TABLE_COLUMN_PORTRAIT_STATUS_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_STATUS_BAR_HEIGHT_KEY;
$TABLE_COLUMN_PORTRAIT_TITLE_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_PORTRAIT . $REQUEST_TITLE_BAR_HEIGHT_KEY;

$TABLE_COLUMN_LANDSCAPE_DEVICE_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_DEVICE_PIXEL_HEIGHT_KEY ;
$TABLE_COLUMN_LANDSCAPE_DEVICE_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_DEVICE_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_LANDSCAPE_WINDOW_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_WINDOW_PIXEL_HEIGHT_KEY;
$TABLE_COLUMN_LANDSCAPE_WINDOW_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_WINDOW_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_LANDSCAPE_CONTENT_VIEW_PIXEL_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_CONTENT_VIEW_PIXEL_HEIGHT_KEY;
$TABLE_COLUMN_LANDSCAPE_CONTENT_VIEW_PIXEL_WIDTH_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_CONTENT_VIEW_PIXEL_WIDTH_KEY;
$TABLE_COLUMN_LANDSCAPE_NAV_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_NAV_BAR_HEIGHT_KEY;
$TABLE_COLUMN_LANDSCAPE_NAV_BAR_WIDTH_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_NAV_BAR_WIDTH_KEY;
$TABLE_COLUMN_LANDSCAPE_STATUS_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_STATUS_BAR_HEIGHT_KEY;
$TABLE_COLUMN_LANDSCAPE_TITLE_BAR_HEIGHT_KEY = $TABLE_COLUMN_NAME_LANDSCAPE . $REQUEST_TITLE_BAR_HEIGHT_KEY;


$HTML_TABLE_DEVICE_NAME = "Device name";

?>
